# Generated by Django 5.2.7 on 2026-05-18 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentprovider_alter_transaction_options_and_more'),
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgatewaylog',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateway_logs', to='station.transaction'),
        ),
        migrations.AddField(
            model_name='paymentgatewaylog',
            name='reference',
            field=models.CharField(blank=True, help_text='Paystack transaction reference', max_length=100),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
