# Generated by Django 6.0.4 on 2026-05-21 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_paymentgatewaylog_transaction_and_more'),
        ('station', '0003_payment_customer_email_payment_customer_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('payment_verified', 'Payment Verified'), ('payment_saved', 'Payment Saved'), ('sms_queued', 'SMS Queued'), ('sms_sent', 'SMS Sent'), ('sms_failed', 'SMS Failed'), ('sms_retry', 'SMS Retry Scheduled'), ('sms_skipped', 'SMS Skipped'), ('admin_action', 'Admin Action'), ('webhook_verified', 'Webhook Verified'), ('webhook_rejected', 'Webhook Rejected')], max_length=50)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='station.payment')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='station.transaction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('payment_confirmation', 'Payment Confirmation'), ('test_sms', 'Test SMS'), ('receipt_sms', 'Receipt SMS')], default='payment_confirmation', max_length=50)),
                ('provider', models.CharField(max_length=50)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('reference', models.CharField(db_index=True, max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('sent', 'Sent'), ('retrying', 'Retrying'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('provider_message_id', models.CharField(blank=True, max_length=120)),
                ('provider_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_delivery_logs', to='station.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('reference', 'purpose'), name='uniq_sms_delivery_reference_purpose')],
            },
        ),
    ]
