# Generated by Django 5.2.7 on 2026-05-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_userprofile_address_userprofile_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_date', models.DateField(unique=True)),
                ('today_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('total_fuel_dispensed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending_payments', models.PositiveIntegerField(default=0)),
                ('last_transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('last_transaction_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-summary_date'],
            },
        ),
    ]
