# Generated by Django 6.0.4 on 2026-05-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_alter_transaction_fuel_type_alter_transaction_pump'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
